/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.9.5
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QListView>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStackedWidget>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTableView>
#include <QtWidgets/QToolBar>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralWidget;
    QStackedWidget *stackedWidget;
    QWidget *page;
    QPushButton *pushButton_4;
    QPushButton *pushButton_3;
    QLabel *label_14;
    QLabel *label_15;
    QWidget *page_2;
    QPushButton *pushButton_7;
    QLabel *label;
    QLabel *label_16;
    QPushButton *pushButton_13;
    QWidget *page_3;
    QPushButton *pushButton;
    QPushButton *pushButton_2;
    QLabel *label_2;
    QLabel *label_17;
    QPushButton *pushButton_11;
    QPushButton *pushButton_12;
    QPushButton *pushButton_18;
    QWidget *page_4;
    QTableView *tableView;
    QPushButton *pushButton_5;
    QPushButton *pushButton_6;
    QLabel *label_3;
    QLabel *label_18;
    QWidget *page_5;
    QTableView *tableView_2;
    QLineEdit *lineEdit_16;
    QLabel *label_4;
    QLabel *label_5;
    QLabel *label_6;
    QLabel *label_7;
    QLabel *label_8;
    QLabel *label_9;
    QLabel *label_10;
    QLabel *label_11;
    QLabel *label_12;
    QLabel *label_13;
    QLineEdit *lineEdit_17;
    QLineEdit *lineEdit_18;
    QLineEdit *lineEdit_19;
    QLineEdit *lineEdit_20;
    QLineEdit *lineEdit_21;
    QLineEdit *lineEdit_22;
    QLineEdit *lineEdit_23;
    QLineEdit *lineEdit_24;
    QLineEdit *lineEdit_25;
    QPushButton *pushButton_8;
    QPushButton *pushButton_9;
    QPushButton *pushButton_10;
    QLabel *label_19;
    QLabel *label_20;
    QLineEdit *lineEdit_26;
    QLabel *label_21;
    QLineEdit *lineEdit_27;
    QLineEdit *lineEdit_28;
    QLineEdit *lineEdit_29;
    QLineEdit *lineEdit_30;
    QLabel *label_26;
    QLabel *label_27;
    QLabel *label_28;
    QLineEdit *lineEdit_31;
    QLabel *label_29;
    QListView *listView_2;
    QPushButton *pushButton_22;
    QComboBox *comboBox;
    QPushButton *pushButton_24;
    QWidget *page_6;
    QLabel *label_22;
    QTableView *tableView_3;
    QLabel *label_23;
    QPushButton *pushButton_16;
    QPushButton *pushButton_17;
    QWidget *page_7;
    QLabel *label_24;
    QTableView *tableView_4;
    QLabel *label_25;
    QPushButton *pushButton_14;
    QPushButton *pushButton_15;
    QWidget *page_8;
    QLabel *label_30;
    QTableView *tableView_5;
    QPushButton *pushButton_19;
    QPushButton *pushButton_20;
    QPushButton *pushButton_21;
    QLabel *label_31;
    QLineEdit *lineEdit_32;
    QLabel *label_32;
    QLabel *label_33;
    QLineEdit *lineEdit_33;
    QLabel *label_34;
    QLineEdit *lineEdit_34;
    QComboBox *comboBox_2;
    QListView *listView_3;
    QPushButton *pushButton_23;
    QPushButton *pushButton_25;
    QMenuBar *menuBar;
    QToolBar *mainToolBar;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QStringLiteral("MainWindow"));
        MainWindow->resize(903, 606);
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QStringLiteral("centralWidget"));
        stackedWidget = new QStackedWidget(centralWidget);
        stackedWidget->setObjectName(QStringLiteral("stackedWidget"));
        stackedWidget->setGeometry(QRect(0, 0, 903, 561));
        page = new QWidget();
        page->setObjectName(QStringLiteral("page"));
        pushButton_4 = new QPushButton(page);
        pushButton_4->setObjectName(QStringLiteral("pushButton_4"));
        pushButton_4->setGeometry(QRect(160, 370, 141, 51));
        QFont font;
        font.setPointSize(10);
        pushButton_4->setFont(font);
        pushButton_3 = new QPushButton(page);
        pushButton_3->setObjectName(QStringLiteral("pushButton_3"));
        pushButton_3->setGeometry(QRect(590, 370, 141, 51));
        pushButton_3->setFont(font);
        label_14 = new QLabel(page);
        label_14->setObjectName(QStringLiteral("label_14"));
        label_14->setGeometry(QRect(330, 160, 221, 51));
        QFont font1;
        font1.setPointSize(50);
        label_14->setFont(font1);
        label_15 = new QLabel(page);
        label_15->setObjectName(QStringLiteral("label_15"));
        label_15->setGeometry(QRect(0, 0, 121, 41));
        QFont font2;
        font2.setPointSize(15);
        label_15->setFont(font2);
        stackedWidget->addWidget(page);
        page_2 = new QWidget();
        page_2->setObjectName(QStringLiteral("page_2"));
        pushButton_7 = new QPushButton(page_2);
        pushButton_7->setObjectName(QStringLiteral("pushButton_7"));
        pushButton_7->setGeometry(QRect(210, 350, 141, 51));
        pushButton_7->setFont(font);
        label = new QLabel(page_2);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(280, 120, 311, 61));
        QFont font3;
        font3.setPointSize(30);
        label->setFont(font3);
        label_16 = new QLabel(page_2);
        label_16->setObjectName(QStringLiteral("label_16"));
        label_16->setGeometry(QRect(0, 0, 121, 41));
        label_16->setFont(font2);
        pushButton_13 = new QPushButton(page_2);
        pushButton_13->setObjectName(QStringLiteral("pushButton_13"));
        pushButton_13->setGeometry(QRect(530, 350, 141, 51));
        pushButton_13->setFont(font);
        stackedWidget->addWidget(page_2);
        page_3 = new QWidget();
        page_3->setObjectName(QStringLiteral("page_3"));
        pushButton = new QPushButton(page_3);
        pushButton->setObjectName(QStringLiteral("pushButton"));
        pushButton->setGeometry(QRect(220, 350, 91, 31));
        pushButton->setFont(font);
        pushButton_2 = new QPushButton(page_3);
        pushButton_2->setObjectName(QStringLiteral("pushButton_2"));
        pushButton_2->setGeometry(QRect(570, 350, 91, 31));
        label_2 = new QLabel(page_3);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(290, 130, 311, 61));
        label_2->setFont(font3);
        label_17 = new QLabel(page_3);
        label_17->setObjectName(QStringLiteral("label_17"));
        label_17->setGeometry(QRect(0, 0, 121, 41));
        label_17->setFont(font2);
        pushButton_11 = new QPushButton(page_3);
        pushButton_11->setObjectName(QStringLiteral("pushButton_11"));
        pushButton_11->setGeometry(QRect(400, 430, 91, 31));
        pushButton_11->setFont(font);
        pushButton_12 = new QPushButton(page_3);
        pushButton_12->setObjectName(QStringLiteral("pushButton_12"));
        pushButton_12->setGeometry(QRect(220, 390, 91, 31));
        pushButton_12->setFont(font);
        pushButton_18 = new QPushButton(page_3);
        pushButton_18->setObjectName(QStringLiteral("pushButton_18"));
        pushButton_18->setGeometry(QRect(570, 390, 91, 31));
        stackedWidget->addWidget(page_3);
        page_4 = new QWidget();
        page_4->setObjectName(QStringLiteral("page_4"));
        tableView = new QTableView(page_4);
        tableView->setObjectName(QStringLiteral("tableView"));
        tableView->setGeometry(QRect(60, 100, 791, 241));
        pushButton_5 = new QPushButton(page_4);
        pushButton_5->setObjectName(QStringLiteral("pushButton_5"));
        pushButton_5->setGeometry(QRect(160, 380, 141, 51));
        pushButton_5->setFont(font);
        pushButton_6 = new QPushButton(page_4);
        pushButton_6->setObjectName(QStringLiteral("pushButton_6"));
        pushButton_6->setGeometry(QRect(570, 380, 141, 51));
        pushButton_6->setFont(font);
        label_3 = new QLabel(page_4);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(310, 30, 311, 61));
        label_3->setFont(font3);
        label_18 = new QLabel(page_4);
        label_18->setObjectName(QStringLiteral("label_18"));
        label_18->setGeometry(QRect(0, 0, 121, 41));
        label_18->setFont(font2);
        stackedWidget->addWidget(page_4);
        page_5 = new QWidget();
        page_5->setObjectName(QStringLiteral("page_5"));
        tableView_2 = new QTableView(page_5);
        tableView_2->setObjectName(QStringLiteral("tableView_2"));
        tableView_2->setGeometry(QRect(380, 40, 451, 331));
        lineEdit_16 = new QLineEdit(page_5);
        lineEdit_16->setObjectName(QStringLiteral("lineEdit_16"));
        lineEdit_16->setGeometry(QRect(110, 290, 111, 25));
        label_4 = new QLabel(page_5);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(30, 20, 31, 21));
        label_5 = new QLabel(page_5);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(30, 50, 41, 21));
        label_6 = new QLabel(page_5);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(30, 80, 41, 21));
        label_7 = new QLabel(page_5);
        label_7->setObjectName(QStringLiteral("label_7"));
        label_7->setGeometry(QRect(30, 110, 31, 21));
        label_8 = new QLabel(page_5);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(30, 140, 41, 21));
        label_9 = new QLabel(page_5);
        label_9->setObjectName(QStringLiteral("label_9"));
        label_9->setGeometry(QRect(30, 170, 41, 21));
        label_10 = new QLabel(page_5);
        label_10->setObjectName(QStringLiteral("label_10"));
        label_10->setGeometry(QRect(30, 200, 51, 21));
        label_11 = new QLabel(page_5);
        label_11->setObjectName(QStringLiteral("label_11"));
        label_11->setGeometry(QRect(30, 230, 31, 21));
        label_12 = new QLabel(page_5);
        label_12->setObjectName(QStringLiteral("label_12"));
        label_12->setGeometry(QRect(30, 260, 51, 21));
        label_13 = new QLabel(page_5);
        label_13->setObjectName(QStringLiteral("label_13"));
        label_13->setGeometry(QRect(30, 290, 71, 21));
        lineEdit_17 = new QLineEdit(page_5);
        lineEdit_17->setObjectName(QStringLiteral("lineEdit_17"));
        lineEdit_17->setGeometry(QRect(90, 260, 131, 25));
        lineEdit_18 = new QLineEdit(page_5);
        lineEdit_18->setObjectName(QStringLiteral("lineEdit_18"));
        lineEdit_18->setGeometry(QRect(60, 230, 161, 25));
        lineEdit_19 = new QLineEdit(page_5);
        lineEdit_19->setObjectName(QStringLiteral("lineEdit_19"));
        lineEdit_19->setGeometry(QRect(80, 200, 141, 25));
        lineEdit_20 = new QLineEdit(page_5);
        lineEdit_20->setObjectName(QStringLiteral("lineEdit_20"));
        lineEdit_20->setGeometry(QRect(70, 170, 151, 25));
        lineEdit_21 = new QLineEdit(page_5);
        lineEdit_21->setObjectName(QStringLiteral("lineEdit_21"));
        lineEdit_21->setGeometry(QRect(60, 140, 161, 25));
        lineEdit_22 = new QLineEdit(page_5);
        lineEdit_22->setObjectName(QStringLiteral("lineEdit_22"));
        lineEdit_22->setGeometry(QRect(60, 110, 161, 25));
        lineEdit_23 = new QLineEdit(page_5);
        lineEdit_23->setObjectName(QStringLiteral("lineEdit_23"));
        lineEdit_23->setGeometry(QRect(70, 80, 151, 25));
        lineEdit_24 = new QLineEdit(page_5);
        lineEdit_24->setObjectName(QStringLiteral("lineEdit_24"));
        lineEdit_24->setGeometry(QRect(80, 50, 141, 25));
        lineEdit_25 = new QLineEdit(page_5);
        lineEdit_25->setObjectName(QStringLiteral("lineEdit_25"));
        lineEdit_25->setGeometry(QRect(70, 20, 151, 25));
        pushButton_8 = new QPushButton(page_5);
        pushButton_8->setObjectName(QStringLiteral("pushButton_8"));
        pushButton_8->setGeometry(QRect(250, 440, 83, 25));
        pushButton_9 = new QPushButton(page_5);
        pushButton_9->setObjectName(QStringLiteral("pushButton_9"));
        pushButton_9->setGeometry(QRect(530, 420, 141, 51));
        pushButton_9->setFont(font);
        pushButton_10 = new QPushButton(page_5);
        pushButton_10->setObjectName(QStringLiteral("pushButton_10"));
        pushButton_10->setGeometry(QRect(250, 470, 83, 25));
        label_19 = new QLabel(page_5);
        label_19->setObjectName(QStringLiteral("label_19"));
        label_19->setGeometry(QRect(550, 0, 121, 41));
        label_19->setFont(font2);
        label_20 = new QLabel(page_5);
        label_20->setObjectName(QStringLiteral("label_20"));
        label_20->setGeometry(QRect(30, 320, 61, 21));
        lineEdit_26 = new QLineEdit(page_5);
        lineEdit_26->setObjectName(QStringLiteral("lineEdit_26"));
        lineEdit_26->setGeometry(QRect(90, 320, 131, 25));
        label_21 = new QLabel(page_5);
        label_21->setObjectName(QStringLiteral("label_21"));
        label_21->setGeometry(QRect(30, 350, 81, 21));
        lineEdit_27 = new QLineEdit(page_5);
        lineEdit_27->setObjectName(QStringLiteral("lineEdit_27"));
        lineEdit_27->setGeometry(QRect(110, 350, 111, 25));
        lineEdit_28 = new QLineEdit(page_5);
        lineEdit_28->setObjectName(QStringLiteral("lineEdit_28"));
        lineEdit_28->setGeometry(QRect(100, 380, 121, 25));
        lineEdit_29 = new QLineEdit(page_5);
        lineEdit_29->setObjectName(QStringLiteral("lineEdit_29"));
        lineEdit_29->setGeometry(QRect(100, 410, 121, 25));
        lineEdit_30 = new QLineEdit(page_5);
        lineEdit_30->setObjectName(QStringLiteral("lineEdit_30"));
        lineEdit_30->setGeometry(QRect(100, 440, 121, 25));
        label_26 = new QLabel(page_5);
        label_26->setObjectName(QStringLiteral("label_26"));
        label_26->setGeometry(QRect(30, 380, 61, 21));
        label_27 = new QLabel(page_5);
        label_27->setObjectName(QStringLiteral("label_27"));
        label_27->setGeometry(QRect(30, 410, 61, 21));
        label_28 = new QLabel(page_5);
        label_28->setObjectName(QStringLiteral("label_28"));
        label_28->setGeometry(QRect(30, 440, 61, 21));
        lineEdit_31 = new QLineEdit(page_5);
        lineEdit_31->setObjectName(QStringLiteral("lineEdit_31"));
        lineEdit_31->setGeometry(QRect(90, 470, 131, 25));
        label_29 = new QLabel(page_5);
        label_29->setObjectName(QStringLiteral("label_29"));
        label_29->setGeometry(QRect(30, 470, 51, 21));
        listView_2 = new QListView(page_5);
        listView_2->setObjectName(QStringLiteral("listView_2"));
        listView_2->setGeometry(QRect(240, 90, 121, 281));
        pushButton_22 = new QPushButton(page_5);
        pushButton_22->setObjectName(QStringLiteral("pushButton_22"));
        pushButton_22->setGeometry(QRect(250, 380, 83, 25));
        comboBox = new QComboBox(page_5);
        comboBox->setObjectName(QStringLiteral("comboBox"));
        comboBox->setGeometry(QRect(240, 40, 121, 31));
        pushButton_24 = new QPushButton(page_5);
        pushButton_24->setObjectName(QStringLiteral("pushButton_24"));
        pushButton_24->setGeometry(QRect(340, 380, 83, 25));
        stackedWidget->addWidget(page_5);
        page_6 = new QWidget();
        page_6->setObjectName(QStringLiteral("page_6"));
        label_22 = new QLabel(page_6);
        label_22->setObjectName(QStringLiteral("label_22"));
        label_22->setGeometry(QRect(0, 0, 121, 41));
        label_22->setFont(font2);
        tableView_3 = new QTableView(page_6);
        tableView_3->setObjectName(QStringLiteral("tableView_3"));
        tableView_3->setGeometry(QRect(250, 100, 401, 241));
        label_23 = new QLabel(page_6);
        label_23->setObjectName(QStringLiteral("label_23"));
        label_23->setGeometry(QRect(290, 40, 311, 61));
        label_23->setFont(font3);
        pushButton_16 = new QPushButton(page_6);
        pushButton_16->setObjectName(QStringLiteral("pushButton_16"));
        pushButton_16->setGeometry(QRect(200, 370, 141, 51));
        pushButton_16->setFont(font);
        pushButton_17 = new QPushButton(page_6);
        pushButton_17->setObjectName(QStringLiteral("pushButton_17"));
        pushButton_17->setGeometry(QRect(520, 370, 141, 51));
        pushButton_17->setFont(font);
        stackedWidget->addWidget(page_6);
        page_7 = new QWidget();
        page_7->setObjectName(QStringLiteral("page_7"));
        label_24 = new QLabel(page_7);
        label_24->setObjectName(QStringLiteral("label_24"));
        label_24->setGeometry(QRect(0, 0, 121, 41));
        label_24->setFont(font2);
        tableView_4 = new QTableView(page_7);
        tableView_4->setObjectName(QStringLiteral("tableView_4"));
        tableView_4->setGeometry(QRect(60, 130, 791, 241));
        label_25 = new QLabel(page_7);
        label_25->setObjectName(QStringLiteral("label_25"));
        label_25->setGeometry(QRect(300, 50, 311, 61));
        label_25->setFont(font3);
        pushButton_14 = new QPushButton(page_7);
        pushButton_14->setObjectName(QStringLiteral("pushButton_14"));
        pushButton_14->setGeometry(QRect(190, 400, 141, 51));
        pushButton_14->setFont(font);
        pushButton_15 = new QPushButton(page_7);
        pushButton_15->setObjectName(QStringLiteral("pushButton_15"));
        pushButton_15->setGeometry(QRect(530, 400, 141, 51));
        pushButton_15->setFont(font);
        stackedWidget->addWidget(page_7);
        page_8 = new QWidget();
        page_8->setObjectName(QStringLiteral("page_8"));
        label_30 = new QLabel(page_8);
        label_30->setObjectName(QStringLiteral("label_30"));
        label_30->setGeometry(QRect(0, 0, 121, 41));
        label_30->setFont(font2);
        tableView_5 = new QTableView(page_8);
        tableView_5->setObjectName(QStringLiteral("tableView_5"));
        tableView_5->setGeometry(QRect(390, 70, 451, 331));
        pushButton_19 = new QPushButton(page_8);
        pushButton_19->setObjectName(QStringLiteral("pushButton_19"));
        pushButton_19->setGeometry(QRect(540, 430, 141, 51));
        pushButton_19->setFont(font);
        pushButton_20 = new QPushButton(page_8);
        pushButton_20->setObjectName(QStringLiteral("pushButton_20"));
        pushButton_20->setGeometry(QRect(50, 190, 83, 25));
        pushButton_21 = new QPushButton(page_8);
        pushButton_21->setObjectName(QStringLiteral("pushButton_21"));
        pushButton_21->setGeometry(QRect(150, 190, 83, 25));
        label_31 = new QLabel(page_8);
        label_31->setObjectName(QStringLiteral("label_31"));
        label_31->setGeometry(QRect(550, 20, 121, 41));
        label_31->setFont(font2);
        lineEdit_32 = new QLineEdit(page_8);
        lineEdit_32->setObjectName(QStringLiteral("lineEdit_32"));
        lineEdit_32->setGeometry(QRect(80, 60, 151, 25));
        label_32 = new QLabel(page_8);
        label_32->setObjectName(QStringLiteral("label_32"));
        label_32->setGeometry(QRect(60, 60, 16, 21));
        label_33 = new QLabel(page_8);
        label_33->setObjectName(QStringLiteral("label_33"));
        label_33->setGeometry(QRect(60, 100, 41, 21));
        lineEdit_33 = new QLineEdit(page_8);
        lineEdit_33->setObjectName(QStringLiteral("lineEdit_33"));
        lineEdit_33->setGeometry(QRect(100, 100, 131, 25));
        label_34 = new QLabel(page_8);
        label_34->setObjectName(QStringLiteral("label_34"));
        label_34->setGeometry(QRect(60, 140, 61, 21));
        lineEdit_34 = new QLineEdit(page_8);
        lineEdit_34->setObjectName(QStringLiteral("lineEdit_34"));
        lineEdit_34->setGeometry(QRect(120, 140, 111, 25));
        comboBox_2 = new QComboBox(page_8);
        comboBox_2->setObjectName(QStringLiteral("comboBox_2"));
        comboBox_2->setGeometry(QRect(250, 60, 121, 31));
        listView_3 = new QListView(page_8);
        listView_3->setObjectName(QStringLiteral("listView_3"));
        listView_3->setGeometry(QRect(250, 120, 121, 281));
        pushButton_23 = new QPushButton(page_8);
        pushButton_23->setObjectName(QStringLiteral("pushButton_23"));
        pushButton_23->setGeometry(QRect(270, 410, 83, 25));
        pushButton_25 = new QPushButton(page_8);
        pushButton_25->setObjectName(QStringLiteral("pushButton_25"));
        pushButton_25->setGeometry(QRect(270, 440, 83, 25));
        stackedWidget->addWidget(page_8);
        MainWindow->setCentralWidget(centralWidget);
        menuBar = new QMenuBar(MainWindow);
        menuBar->setObjectName(QStringLiteral("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 903, 22));
        MainWindow->setMenuBar(menuBar);
        mainToolBar = new QToolBar(MainWindow);
        mainToolBar->setObjectName(QStringLiteral("mainToolBar"));
        MainWindow->addToolBar(Qt::TopToolBarArea, mainToolBar);
        statusBar = new QStatusBar(MainWindow);
        statusBar->setObjectName(QStringLiteral("statusBar"));
        MainWindow->setStatusBar(statusBar);

        retranslateUi(MainWindow);

        stackedWidget->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "MainWindow", Q_NULLPTR));
        pushButton_4->setText(QApplication::translate("MainWindow", "Client", Q_NULLPTR));
        pushButton_3->setText(QApplication::translate("MainWindow", "Staff", Q_NULLPTR));
        label_14->setText(QApplication::translate("MainWindow", "cuACS", Q_NULLPTR));
        label_15->setText(QApplication::translate("MainWindow", "4our People", Q_NULLPTR));
        pushButton_7->setText(QApplication::translate("MainWindow", "Back", Q_NULLPTR));
        label->setText(QString());
        label_16->setText(QApplication::translate("MainWindow", "4our People", Q_NULLPTR));
        pushButton_13->setText(QApplication::translate("MainWindow", "View Animals", Q_NULLPTR));
        pushButton->setText(QApplication::translate("MainWindow", "View Animals", Q_NULLPTR));
        pushButton_2->setText(QApplication::translate("MainWindow", "Add Animal", Q_NULLPTR));
        label_2->setText(QString());
        label_17->setText(QApplication::translate("MainWindow", "4our People", Q_NULLPTR));
        pushButton_11->setText(QApplication::translate("MainWindow", "Back", Q_NULLPTR));
        pushButton_12->setText(QApplication::translate("MainWindow", "View Clients", Q_NULLPTR));
        pushButton_18->setText(QApplication::translate("MainWindow", "Add Client", Q_NULLPTR));
        pushButton_5->setText(QApplication::translate("MainWindow", "Back", Q_NULLPTR));
        pushButton_6->setText(QApplication::translate("MainWindow", "Homepage", Q_NULLPTR));
        label_3->setText(QString());
        label_18->setText(QApplication::translate("MainWindow", "4our People", Q_NULLPTR));
        label_4->setText(QApplication::translate("MainWindow", "Type", Q_NULLPTR));
        label_5->setText(QApplication::translate("MainWindow", "Breed", Q_NULLPTR));
        label_6->setText(QApplication::translate("MainWindow", "Name", Q_NULLPTR));
        label_7->setText(QApplication::translate("MainWindow", "Sex", Q_NULLPTR));
        label_8->setText(QApplication::translate("MainWindow", "Age", Q_NULLPTR));
        label_9->setText(QApplication::translate("MainWindow", "Social", Q_NULLPTR));
        label_10->setText(QApplication::translate("MainWindow", "Health", Q_NULLPTR));
        label_11->setText(QApplication::translate("MainWindow", "Diet", Q_NULLPTR));
        label_12->setText(QApplication::translate("MainWindow", "Trained", Q_NULLPTR));
        label_13->setText(QApplication::translate("MainWindow", "Nocturnal", Q_NULLPTR));
        pushButton_8->setText(QApplication::translate("MainWindow", "Save", Q_NULLPTR));
        pushButton_9->setText(QApplication::translate("MainWindow", "Homepage", Q_NULLPTR));
        pushButton_10->setText(QApplication::translate("MainWindow", "Back", Q_NULLPTR));
        label_19->setText(QApplication::translate("MainWindow", "4our People", Q_NULLPTR));
        label_20->setText(QApplication::translate("MainWindow", "Emotion", Q_NULLPTR));
        label_21->setText(QApplication::translate("MainWindow", "Pet's Worth", Q_NULLPTR));
        label_26->setText(QApplication::translate("MainWindow", "Has Kids", Q_NULLPTR));
        label_27->setText(QApplication::translate("MainWindow", "Allergies", Q_NULLPTR));
        label_28->setText(QApplication::translate("MainWindow", "Stability", Q_NULLPTR));
        label_29->setText(QApplication::translate("MainWindow", "Housing", Q_NULLPTR));
        pushButton_22->setText(QApplication::translate("MainWindow", "Load", Q_NULLPTR));
        pushButton_24->setText(QApplication::translate("MainWindow", "Clear", Q_NULLPTR));
        label_22->setText(QApplication::translate("MainWindow", "4our People", Q_NULLPTR));
        label_23->setText(QString());
        pushButton_16->setText(QApplication::translate("MainWindow", "Back", Q_NULLPTR));
        pushButton_17->setText(QApplication::translate("MainWindow", "Homepage", Q_NULLPTR));
        label_24->setText(QApplication::translate("MainWindow", "4our People", Q_NULLPTR));
        label_25->setText(QString());
        pushButton_14->setText(QApplication::translate("MainWindow", "Back", Q_NULLPTR));
        pushButton_15->setText(QApplication::translate("MainWindow", "Homepage", Q_NULLPTR));
        label_30->setText(QApplication::translate("MainWindow", "4our People", Q_NULLPTR));
        pushButton_19->setText(QApplication::translate("MainWindow", "Homepage", Q_NULLPTR));
        pushButton_20->setText(QApplication::translate("MainWindow", "Save", Q_NULLPTR));
        pushButton_21->setText(QApplication::translate("MainWindow", "Back", Q_NULLPTR));
        label_31->setText(QApplication::translate("MainWindow", "4our People", Q_NULLPTR));
        label_32->setText(QApplication::translate("MainWindow", "id", Q_NULLPTR));
        label_33->setText(QApplication::translate("MainWindow", "Name", Q_NULLPTR));
        label_34->setText(QApplication::translate("MainWindow", "Address", Q_NULLPTR));
        pushButton_23->setText(QApplication::translate("MainWindow", "Load", Q_NULLPTR));
        pushButton_25->setText(QApplication::translate("MainWindow", "Clear", Q_NULLPTR));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
